preset.1.20.4.minecraft_version=1.20.4
preset.1.20.4.minecraft_version_range=[1.20.4,1.20.5)
preset.1.20.4.fabric_api_version=0.97.3+1.20.4
preset.1.20.4.fabric_loader_version=0.17.2
preset.1.20.4.modmenu_version=9.0.0
preset.1.20.4.cloth_config_version=13.0.121
preset.1.20.4.iris_version=1.7.0+1.20.4
preset.1.20.4.sodium_version=mc1.20.4-0.5.8
preset.1.20.4.forge_version=1.20.4-49.0.38
preset.1.20.4.forge_loader_version_range=[49,)

preset.1.20.1.minecraft_version=1.20.1
preset.1.20.1.minecraft_version_range=[1.20.1,1.20.2)
preset.1.20.1.fabric_api_version=0.92.9+1.20.1
preset.1.20.1.fabric_loader_version=0.16.10
preset.1.20.1.modmenu_version=7.2.2
preset.1.20.1.cloth_config_version=11.1.136
preset.1.20.1.iris_version=1.7.6+1.20.1
preset.1.20.1.sodium_version=mc1.20.1-0.5.13-fabric
preset.1.20.1.forge_version=1.20.1-47.4.20
preset.1.20.1.forge_loader_version_range=[47,)

preset.1.19.2.minecraft_version=1.19.2
preset.1.19.2.minecraft_version_range=[1.19.2,1.19.3)
preset.1.19.2.fabric_api_version=0.77.0+1.19.2
preset.1.19.2.fabric_loader_version=0.16.10
preset.1.19.2.modmenu_version=4.1.2
preset.1.19.2.cloth_config_version=8.3.103
preset.1.19.2.iris_version=1.6.11+1.19.2
preset.1.19.2.sodium_version=mc1.19.2-0.4.4
preset.1.19.2.forge_version=1.19.2-43.5.2
preset.1.19.2.forge_loader_version_range=[43,)

preset.1.18.2.minecraft_version=1.18.2
preset.1.18.2.minecraft_version_range=[1.18.2,1.19)
preset.1.18.2.fabric_api_version=0.77.0+1.18.2
preset.1.18.2.fabric_loader_version=0.16.10
preset.1.18.2.modmenu_version=3.2.5
preset.1.18.2.cloth_config_version=6.5.116
preset.1.18.2.iris_version=1.6.11+1.18.2
preset.1.18.2.sodium_version=mc1.18.2-0.4.1
preset.1.18.2.forge_version=1.18.2-40.3.12
preset.1.18.2.forge_loader_version_range=[40,)
